In [1]:
# Example of bokeh layout plotting.
# Authors: Huang Xiao 
# Affiliation: Fraunhofer AISEC Institute, Munich, Germany 
# Copyright@2016

import sklearn.datasets as mydata
from bokeh.plotting import figure, output_notebook, show
from bokeh.layouts import Row, Column, gridplot, layout
from sklearn.decomposition import PCA
from bokeh.palettes import BrBG5


output_notebook()
loaded_digits_data = mydata.load_digits()
Xtr, ytr = loaded_digits_data.data, loaded_digits_data.target
f1 = figure(width=200, height=200, toolbar_location='above')
f2 = figure(width=200, height=200, toolbar_location='above')
f3 = figure(width=200, height=200, toolbar_location='above')
f4 = figure(width=200, height=200, toolbar_location='above')
pca = PCA(n_components = 2)
Xtr2d = pca.fit_transform(Xtr)
f1.circle(Xtr2d[:,0], Xtr2d[:,1], size=4)
f2.circle(Xtr2d[:,0], Xtr2d[:,1], size=4)
f3.circle(Xtr2d[:,0], Xtr2d[:,1], size=4)

show(gridplot([f1, f2, f3], ncols=3))



Loading BokehJS ...

In [25]:
import tensorflow as tf

x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

op = tf.add(x, y)
with tf.Session() as sess:
    res = sess.run(op, feed_dict={x: [[1,2,3], [1,2,3], [1,1,1,]], y: 1})
    print res
    

[[ 2.  3.  4.]
 [ 2.  3.  4.]
 [ 2.  2.  2.]]


In [4]:
import pandas as pd
from bokeh.charts import output_file, Chord
from bokeh.io import show
from bokeh.sampledata.les_mis import data

nodes = data['nodes']
links = data['links']

nodes_df = pd.DataFrame(nodes)
links_df = pd.DataFrame(links)

source_data = links_df.merge(nodes_df, how='left', left_on='source', right_index=True)
source_data = source_data.merge(nodes_df, how='left', left_on='target', right_index=True)
source_data = source_data[source_data["value"] > 10]

chord_from_df = Chord(source_data, source="name_x", target="name_y", value="value")
output_file('chord_from_df.html', mode="inline")
show(chord_from_df)


INFO:bokeh.core.state:Session output file 'chord_from_df.html' already exists, will be overwritten.
